### ISSUE TITLE
Configuration references

### ISSUE THREAD

**Issue by FlyingDR** [FlyingDR/scss-snippets#12]
It is relatively common situation when some part of configuration is same for several non-default modules. Currently it is required to copy / paste it into each module separately. It will be good to be able to create references instead of copying, something like:
```scss
some-key: r-ref(some-config-id),
```

**Comment by FlyingDR** [comment]
It may also be good idea to allow referencing different keys from same or different configuration, so actual signature may look like:
```scss
@function r-ref($key: null, $id: null, $default: null)
```
Actual value stored into sass map may be a list of pre-defined format like:
```scss
__r_ref_v1__ $key $id $default
```
It is important to avoid using maps to avoid issues with response configuration flattening (#13). Value retrieval function will need to handle it like this:
```scss
@if (type-of($value) == list && length($value) == 4 && nth($value, 1) == __r_ref_v1__) {
  $value: r-get(nth($value, 2), nth($value, 4), nth($value, 3));
}
```
