### ISSUE TITLE
r-get() with fallback

### ISSUE THREAD

**Issue by FlyingDR** [FlyingDR/scss-snippets#22]
Sometimes it is useful to be able to get responsive configuration value with fallback to value from default responsive configuration. Example is size calculations that includes responsive offsets that may, or may not be defined for some particular responsive configuration.

 `r-get()` should have support for such feature.

**Comment by FlyingDR** [comment]
Example of how it may look like inside:
```scss
$value: r-get($key, $responsive-default-id);
@if (r-has($key, $id)) {
  $value: r-get($key, $id);
}
```
