### ISSUE TITLE
Potential issue with parsing offsets

### ISSUE THREAD

**Issue by FlyingDR** [FlyingDR/scss-snippets#28]
There is an issue with offsets parser in a case if **part** of offset definition is came from `map-get()`
```scss
$map: (offset: 0 1);
.test {
	@include offset(p map-get($map, offset));
}
```
Expected result:
```css
.test {
  padding: 0 20px;
}
```
Actual result:
```css
.test {
  padding: 0 20px 0 20px 0 20px 0 20px;
}
```
Passing of additional flags as options fixes issue:
```scss
@include offset(map-get($map, offset), p);
```
